first
cheapreats/react-ui-library pull request #176
Opened 2020-09-28 22:29 UTC by roggc

2020-09-28 22:35 UTC, roggc commented
![coupon](https://user-images.githubusercontent.com/29568460/94492913-a7421400-01eb-11eb-9379-4648f1206d56.gif)

2020-09-29 02:31 UTC, ralph-dev commented
Text1 etc are not good variable names. You want to be generic but not too abstract where no one knows what's going on.

Replace text1 with CouponTitle or Title
Text2 with coupon description or Description etc

2020-09-29 02:32 UTC, ralph-dev requested changes
Prop naming needs more work

2020-09-29 02:32 UTC, ralph-dev commented on src/Containers/Coupon.tsx
> +    bg: sring;
color instead would be better

2020-09-29 02:32 UTC, ralph-dev commented on src/Containers/Coupon.tsx
> +    ...rest
...props is the standard

2020-09-29 07:44 UTC, roggc commented
![coupon2](https://user-images.githubusercontent.com/29568460/94528244-67ede480-0238-11eb-93a5-bedfd7a93327.gif)

2020-09-29 14:46 UTC, ralph-dev approved these changes
Lgtm

2020-09-29 15:06 UTC, merged