Table managementv2
cheapreats/react-ui-library pull request #222
Opened 2020-11-06 18:51 UTC by ScottyKnows44

Square, Circle, Rectangle Components with their stories for Storybook

2020-11-06 19:15 UTC, ralph-dev requested changes
Needs improvement

2020-11-06 19:15 UTC, ralph-dev commented on src/Containers/CircleTable.tsx
> +     * Primary function that returns the color from the occupancyStatus
This is not proper JSDOC the parameter is not typed

2020-11-06 19:15 UTC, ralph-dev commented on src/Containers/CircleTable.tsx
> +    const TableBody = styled.div`
Why is there random indents here?

2020-11-06 19:15 UTC, ralph-dev commented on src/Containers/CircleTable.tsx
> +           //color: ${({theme}) => theme.colors.primary};
Remove commented code

2020-11-06 19:16 UTC, ralph-dev commented on src/Containers/RectangleTable.tsx
> +            return 4;
These are magic numbers what does it mean

2020-11-09 20:53 UTC, ralph-dev reviewed
Small addition

2020-11-09 20:53 UTC, ralph-dev commented on src/Containers/CircleTable.tsx
> +export interface ICircleTable { /**
This /** should be on the next line

2020-11-12 00:33 UTC, ralph-dev commented on debug.log
> +[1111/150741.820:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
add this to gitignore

2020-11-12 00:34 UTC, ralph-dev commented on src/Containers/Chair.tsx
> +                return <div><LeftChair /></div>;
why is there an extra div here?

2020-11-12 00:35 UTC, ralph-dev commented on src/Containers/Chair.tsx
> +                return <div />;
why not return null?

2020-11-12 00:35 UTC, ralph-dev commented on src/Containers/Chair.tsx
> +    background-color: #6c757d;
use theme object

2020-11-12 00:36 UTC, ralph-dev commented on src/Containers/Chair.tsx
> +const BottomChair=styled.div`
do BaseChair = styled.div``;
then do 
const RightChair = styled(BaseChair)``;
to reduce duplicate styles

2020-11-17 19:04 UTC, ralph-dev approved these changes
LGTM

2020-11-18 00:01 UTC, rogers-ch commented on src/Containers/Chair.tsx
> +        function chairSwitch(): JSX.Element
Ralph, I updated this with ES6 syntax and solved the conflict in the index.ts file. I can merge the pull request if this looks good to you.

2020-11-18 00:05 UTC, ralph-dev commented on src/Containers/Chair.tsx
> +        const chairSwitch: () => (JSX.Element | null) = () =>
Don't define inline types btw :)

2020-11-18 00:08 UTC, merged