Update Chair, SquareTable, and RectangleTable2 to add chair positioning and create CircleTable2 with chairs around border
cheapreats/react-ui-library pull request #256
Opened 2020-12-05 16:16 UTC by rogers-ch

2020-12-05 16:55 UTC, ralph-dev commented
@rogers-ch can you attach the screenshots in the Pr

2020-12-05 16:57 UTC, ralph-dev reviewed
First round of comments ^

2020-12-05 16:57 UTC, ralph-dev commented on src/Containers/Chair.tsx
>       * Boolean value for whether someone is seated in the chair
No need to say Boolean value, it's implied by typescript type this is repetition

2020-12-05 16:57 UTC, ralph-dev commented on src/Containers/Chair.tsx
> +     * Boolean value for whether the chair is round.
Remove Boolean value

2020-12-05 16:57 UTC, ralph-dev commented on src/Containers/Chair.tsx
> +    if (isRound) {
Put this inside the return statement it looks out of place, 
Do
IsRound ?
GetCurvedCircleChair
:
GetStraightChair

2020-12-11 00:09 UTC, rogers-ch commented on src/Containers/Chair.tsx
> +function getChairColor(isSeated: boolean) {
We're pulling colors from useTheme(). When we tried accessing useTheme() in the styled component, the components wouldn't render in Storybook anymore. Storybook sticks in the loading phase. Is there a particular way to access useTheme() in the styled components?

2020-12-11 00:13 UTC, ralph-dev commented on src/Containers/Chair.tsx
> +function getChairColor(isSeated: boolean) {
You cannot useTheme in the styled component

2020-12-11 00:14 UTC, ralph-dev commented on src/Containers/Chair.tsx
> +function getChairColor(isSeated: boolean) {
Your supposed to do
${(props) => props.theme}

2020-12-11 00:14 UTC, ralph-dev commented on src/Containers/Chair.tsx
> +function getChairColor(isSeated: boolean) {
OR
${({theme}) => theme.Colors etc}

2020-12-21 23:12 UTC, ralph-dev commented on src/Containers/CircleTable2.tsx
> +                numOfChairs < 3
This 3 is a magic number

2020-12-21 23:12 UTC, ralph-dev commented on src/Containers/CircleTable2.tsx
> +            ${({ numOfChairs }) => (numOfChairs < 3 ? 1 : numOfChairs)}
There is quite a bit of logic why not put it all into a function?
Also if you are doing this much logic, chances are your doing something wrong

2020-12-21 23:13 UTC, ralph-dev approved these changes
LGTM, note how the repo no longer uses the Stories Folder as the Component Folder maintains both.

2020-12-21 23:14 UTC, ralph-dev commented
Follow this guide to fix the merge issues btw
https://wolfbeacon.atlassian.net/wiki/spaces/CW/pages/1683030053/3.1+Merge+Conflicts

2020-12-30 01:53 UTC, ralph-dev commented on src/Containers/Chair.tsx
> +    margin-bottom: ${({ relativeSize }) => relativeSize * 0.25}rem;
Group all of these under relative size, way too much variable destructing

2020-12-30 01:54 UTC, ralph-dev commented on src/Containers/Chair.tsx
> +    margin: ${({ relativeSize }) => relativeSize * 1.25}rem;
Same issue , group together

2020-12-30 01:55 UTC, ralph-dev commented on src/Containers/CircleTable.tsx
>          }
Should this live here or in the styled component? If this only affects styling it should be in styled components

2020-12-30 01:55 UTC, ralph-dev commented on src/Containers/CircleTable.tsx
> +    const generateKey: generateKeyType = (pre) => {
Key for what
generateChairKeys??

2020-12-30 01:55 UTC, ralph-dev commented on src/Containers/CircleTable.tsx
> +     * @param pre - a string to append to random number
prefix
not pre?

2020-12-30 01:56 UTC, ralph-dev commented on src/Containers/CircleTable.tsx
> +const minChairsBeforeTableResize = 4;
MIN_CHAIRS_BEFORE_TABLE_RESIZE
MIN_CHAIRS_TABLE_RESIZE_BREAKPOINT 
use SCREMAING_SNAKE_CASE for consts always when static const (Never Changing)

2020-12-30 01:58 UTC, ralph-dev commented on src/Containers/SquareTable/SquareTable.tsx
> +        }
Living in the wrong place, Styled component Logic

2020-12-30 01:58 UTC, ralph-dev commented on src/Containers/SquareTable/SquareTable.tsx
> +        chairNumOnTop * 20 * relativeSize}rem;
Group

2020-12-30 01:58 UTC, ralph-dev requested changes
Lots of Styling needs to be grouped together so that
1) You can write LESS code
2) Code is more maintainable

2020-12-30 20:20 UTC, ralph-dev commented on src/Containers/CircleTable.tsx
> +
why is there random enter lines

2020-12-30 20:20 UTC, ralph-dev commented on src/Containers/SquareTable/SquareTable.tsx
> +
random enter lines?

2020-12-30 20:21 UTC, ralph-dev commented on src/Containers/SquareTable/_ChairRow.tsx
> +        `margin-right: ${-15 * relativeSize}px;
This -15 is a magic number what does it mean?
WHITESPACE_BETWEEN_CHAIR_AND_TABLE?

2020-12-30 20:21 UTC, ralph-dev requested changes
Still Magic Numbers in the Code, not all of them just specific ones

2020-12-30 20:23 UTC, ralph-dev commented
Also there is merge conflicts ^, Merge Master into this Branch fix conflicts, then wait for approval so you can merge into master

2020-12-31 17:26 UTC, ralph-dev approved these changes
LGTM we will do the fixes in another PR

2020-12-31 18:21 UTC, ralph-dev approved these changes
LGTM, you can merge

2020-12-31 18:23 UTC, merged