CEM-2045 box composition
cheapreats/react-ui-library pull request #289
Opened 2021-02-08 22:21 UTC by roggc

do two squares and a rectangle
<img width="517" alt="Screenshot 2021-02-08 at 23 16 33" src="https://user-images.githubusercontent.com/29568460/107288435-bc656400-6a63-11eb-86d8-a6b8ad4d4ae3.png">

2021-02-08 22:42 UTC, ralph-dev commented on src/Containers/BoxComposition/BoxComposition.tsx
> +interface IBoxProps{
Why don't you extend ImageProps???

2021-02-08 22:43 UTC, ralph-dev requested changes
You need to pass ...props to all new components / make sure you are extending the correct interface.

2021-02-09 15:56 UTC, ralph-dev requested changes
Code structure and props need work, almost there

2021-02-09 15:56 UTC, ralph-dev commented on src/Containers/BoxComposition/BoxComposition.stories.tsx
> +            {
This structure won't work, 3 images are part of one set :) try to actually replace the content on the pulse then you will see why :)

2021-02-09 15:56 UTC, ralph-dev commented on src/Containers/BoxComposition/BoxComposition.tsx
> +    withText:boolean;
Why do you need this?
Just do
!!text &&

2021-02-09 16:02 UTC, Ampatte2 commented on src/Containers/BoxComposition/BoxComposition.tsx
> +const Box:React.FC<IBoxProps>=({imgSource,top,left,width,height,withText,text}):React.ReactElement=>
Why is this a FC and not a function called renderBox = (props) => jsx?

2021-02-09 16:03 UTC, Ampatte2 commented on src/Containers/BoxComposition/BoxComposition.tsx
> +export const BoxComposition:React.FC<IBoxCompositionProps>=({data}):React.ReactElement=>
A FC that just maps? Is there additional styling to be included for this? If not I'd rather just export the Box component and for the story map it out for display.

2021-02-11 17:30 UTC, ralph-dev commented on src/Containers/BoxComposition/BoxComposition.stories.tsx
> +            {
[{
mainImage: {imgSources: 'stringUrl',
                top:0,
                left:75,
                width:100,
                height:200,
                text:'bla bla bla',
                id:'0'},
leftImage: {},
rightImage: {}
}, {Set2}]

2021-02-11 19:44 UTC, ralph-dev requested changes
Wrong, no need for two arrays.
[
{MainImage: {}, LeftImage: {}, RightImage: {}},
{MainImage: {}, LeftImage: {}, RightImage: {}}
]
Look above ^

2021-02-11 20:15 UTC, ralph-dev commented on src/Containers/BoxComposition/BoxComposition.stories.tsx
> +                imgSource:['https://dynaimage.cdn.cnn.com/cnn/c_fill,g_auto,w_1200,h_675,ar_16:9/https%3A%2F%2Fcdn.cnn.com%2Fcnnnext%2Fdam%2Fassets%2F210204090136-amanda-gorman-time-cover.jpg'],
imgSource: string
no need for 3 arrays

2021-02-11 20:15 UTC, ralph-dev requested changes
All imgSource should be strings no need for the array of strings

2021-02-11 20:22 UTC, ralph-dev approved these changes
LGTM, make sure the component still works before merging as the structure was modified.

2021-02-11 20:27 UTC, merged