CEM-2130 add search functionality to ListHeader component in react-ui
cheapreats/react-ui-library pull request #295
Opened 2021-02-26 21:09 UTC by roggc

![searchbar](https://user-images.githubusercontent.com/29568460/109355108-07aead80-787f-11eb-93a4-57a8ad533bce.gif)

2021-02-26 21:13 UTC, Ampatte2 commented
Video of how this works at 255px width?

2021-02-26 21:33 UTC, ralph-dev commented on src/Containers/List/ListHeader.tsx
> +const SearchInput=styled(Input)`
use the Existing React-UI Input

2021-02-26 21:34 UTC, ralph-dev requested changes
Expansion Effect is incorrect (It should expand from the Search Icon)
Try Placing a Grey Border around the Icon and Expanding that to get the effect :)

2021-02-26 21:35 UTC, roggc commented on src/Containers/List/ListHeader.tsx
> +const SearchInput=styled(Input)`
Yes, it is the existing React-ui input

2021-02-26 21:36 UTC, Ampatte2 commented
@ralph-dev this style of search is going to be an issue with this component and it's current use cases. It's rarely at fullscreen width. Terminal and dash both use a 255px width for the list.

Possibly make the search drop down below at certain widths?, or transition the search field beneath the header?

2021-02-26 21:53 UTC, ralph-dev commented
> @ralph-dev this style of search is going to be an issue with this component and it's current use cases. It's rarely at fullscreen width. Terminal and dash both use a 255px width for the list.
> 
> Possibly make the search drop down below at certain widths?, or transition the search field beneath the header?

This only searches for Order ID, what would be the issue if it takes up the full width of 255 px?

2021-02-26 22:03 UTC, Ampatte2 commented
It can take up the full 255, right now the search input is inline with the header so it'll look like the small mobile viewport in the second pic.

2021-02-27 15:55 UTC, ralph-dev approved these changes
Lgtm

2021-02-27 15:55 UTC, ralph-dev commented on src/Containers/List/ListHeader.tsx
> +    const stateExpanded=useState(false)
Don't use this , write out both set and the original

2021-02-27 16:23 UTC, merged