CEM-2232 - Added Feature Display Component
cheapreats/react-ui-library pull request #312
Opened 2021-03-15 21:14 UTC by Magduri

![screencapture-192-168-0-18-6006-iframe-html-2021-03-15-17_10_26](https://user-images.githubusercontent.com/63363693/111222017-a5a9b400-85b1-11eb-9fa9-133edb37a726.png)

2021-03-15 23:35 UTC, ralph-dev commented on src/Containers/FeatureDisplay/FeatureDisplay.stories.tsx
> +    featureTitle: 'Beat fraud',
Add FeatureSubtitle

2021-03-15 23:35 UTC, ralph-dev commented on src/Containers/FeatureDisplay/FeatureDisplay.tsx
> +                </SmallText>
Feature SubTitle Prop

2021-03-15 23:38 UTC, ralph-dev commented on src/Containers/FeatureDisplay/FeatureDisplay.tsx
> +    featureTitle: featureTitle,
Delete : featureTitle see what happens it will work

2021-03-15 23:39 UTC, ralph-dev commented on src/Containers/FeatureDisplay/FeatureDisplay.tsx
> +                )}
Try not to rely on Inline Code 
const getentientient = () => {
return highlightTexts.map(
                    (highlightText): React.ReactElement => (
                        <SmallText size="h6" key={highlightText}>
                            <Tick /> {highlightText}
                            <div />
                        </SmallText>
                    ),
                )
};
retun(
{getHighlightedTexts}

2021-03-15 23:39 UTC, ralph-dev commented on src/Containers/FeatureDisplay/FeatureDisplay.tsx
> +                                <ChartWarning color="#c2ccd9" />{' '}
Color & Text.
Create a Function that returns the piece with two paramteres

2021-03-15 23:40 UTC, ralph-dev commented on src/Containers/FeatureDisplay/FeatureDisplay.tsx
> +                                <ChartWarning color="#c2ccd9" />{' '}
const g = (color, text) => {
<GridItem>
                                <ChartDesc color=color" />{' '}
                                <SmallText>{text}</SmallText>
                            </GridItem>
}

2021-03-15 23:41 UTC, ralph-dev requested changes
Show me how this look on Mobile Layout Versus Desktop Layout.

2021-03-18 15:52 UTC, Magduri commented
mobile layout
![screencapture-192-168-0-18-6006-iframe-html-2021-03-18-11_10_45](https://user-images.githubusercontent.com/63363693/111655817-55646900-87e0-11eb-9d60-d80459d41142.png)

2021-03-18 15:54 UTC, ralph-dev commented on src/Containers/FeatureDisplay/FeatureDisplay.tsx
> +    const getImageTags = () => {
Remember to write JSDOC to give these functions a clear description of what they do :)

2021-03-18 15:55 UTC, ralph-dev approved these changes
LGTM, very well done! Let's jump on a call to talk about your next task. In the meantime, Add Comments this and schedule a call!

2021-03-18 21:41 UTC, merged