(CEM-2503) VoiceButton Component
cheapreats/react-ui-library pull request #367
Opened 2021-10-07 22:18 UTC by ericlin11354

CEM-2503 Working on implementing VoiceButton

PR Draft exists to share code with Cat

2021-10-08 02:54 UTC, ralph-dev commented
Also remember to attach a photo of the component to your PR

2021-10-10 20:53 UTC, ericlin11354 commented
Video of component for visualization.
https://user-images.githubusercontent.com/50276107/136712689-a1107294-414d-4a20-9a33-3fd6003974ce.mp4

2021-10-31 01:01 UTC, Curtain64 commented
![screenshot1](https://user-images.githubusercontent.com/47907803/139562494-5284772b-76ea-4bcc-8ed2-6d15e2912eb4.jpg)
![screenshot2](https://user-images.githubusercontent.com/47907803/139562496-9d5ebe84-b38c-4e4d-aa0e-245a3dbddf68.jpg)
We don't really know how to make it so that the color green would only be within the microphone icon but this is our process thus far.

2021-10-31 02:15 UTC, ralph-dev commented
Try reading this: https://developer.mozilla.org/en-US/docs/Web/CSS/mask

2021-10-31 02:27 UTC, ralph-dev requested changes

2021-10-31 02:27 UTC, ralph-dev commented on rollup.config.js
> +<<<<<<< HEAD
Need to fix merge conflicts before merging

2021-11-01 02:27 UTC, Curtain64 commented
![screenshot3](https://user-images.githubusercontent.com/47907803/139613181-6e29ce23-78c6-45a0-adc0-56c39f7b5da8.jpg)
Our screenshot for our VoiceButton

2021-11-13 23:06 UTC, merged