CEM-2547
cheapreats/react-ui-library pull request #388
Opened 2021-11-01 06:15 UTC by Zhuk314

Create an Oval Table and Layout the Chairs around the table.

2021-11-01 06:15 UTC, Zhuk314 commented
![12 chairs](https://user-images.githubusercontent.com/78105676/139629587-e28a5ca0-44a5-490c-9fcd-ff604fd4b5cc.PNG)
![3 chairs](https://user-images.githubusercontent.com/78105676/139629590-9bbf552d-1fdf-4e4e-acdc-ecd2b330fe3e.PNG)
![9 chairs](https://user-images.githubusercontent.com/78105676/139629591-baf1c25f-e951-440b-88f4-ff2bff3e744d.PNG)

2021-11-09 19:31 UTC, ralph-dev commented on src/Containers/OvalTable/OvalTable.stories.tsx
> +            onChairClick: handleOnChairClick,
Use the storybook action event

2021-11-09 19:32 UTC, ralph-dev requested changes

2021-11-09 19:32 UTC, ralph-dev commented on src/Containers/OvalTable/OvalTable.tsx
> +  background-color: gray;
Use theme

2021-11-09 19:32 UTC, ralph-dev commented on src/Containers/OvalTable/OvalTable.tsx
> +    const getChairs: getChairsType = () =>
Missing JSDOC

2021-11-10 01:43 UTC, ralph-dev requested changes

2021-11-10 01:43 UTC, ralph-dev commented on src/Containers/OvalTable/OvalTable.stories.tsx
> +const handleOnChairClick = (
Remove this and replace the console log with storybook actions so it emits the correct event.

action("Log Data")

2021-11-13 23:38 UTC, ralph-dev requested changes

2021-11-13 23:38 UTC, ralph-dev commented on src/Containers/OvalTable/OvalTable.tsx
> +    const translationCoefficient = 1 - (HEIGHT_TO_WIDTH_DIFFERENCE * (quadrantBasedAngle/RIGHT_ANGLE));
This 1 is a magic number

2021-11-13 23:38 UTC, ralph-dev commented on src/Containers/OvalTable/OvalTable.tsx
> +
This is hardcoded, we should check if this works with Jadas Chair she built

2021-11-15 12:47 UTC, ralph-dev approved these changes
Lgtm assuming comments have been resolved.

2021-11-16 00:18 UTC, merged