Created RenderText and OrderDetailsContent components that were refer…
cheapreats/react-ui-library pull request #389
Opened 2021-11-02 03:58 UTC by Emil-Ilnicki

…enced from cheapreats-terminal

2021-11-02 04:01 UTC, Emil-Ilnicki commented
![image](https://user-images.githubusercontent.com/28817337/139784909-29665ec2-29e2-485e-83d3-fd6a6602cf1a.png)
Order List Component containing RenderText components for name and price of item

2021-11-02 04:02 UTC, ralph-dev requested changes

2021-11-02 04:02 UTC, ralph-dev commented on src/Text/RenderText/RenderText.tsx
> +    textProps?: CSSProperties
Why not just props?

2021-11-07 22:24 UTC, ralph-dev commented
Close the PR

2021-11-07 22:59 UTC, closed without merging