Cem 2517
cheapreats/react-ui-library pull request #392
Opened 2021-11-04 23:47 UTC by Hunterjdf

2021-11-04 23:50 UTC, Hunterjdf commented
Hello sir I have been pushing some edge cases since Tuesday. I don't know if you were able to see them before but you should be able to see them now.

2021-11-04 23:57 UTC, Hunterjdf commented
![image](https://user-images.githubusercontent.com/90480884/140435929-e908741d-52cd-4bd1-915d-e6df62c4062b.png)
![image](https://user-images.githubusercontent.com/90480884/140435952-2844aa65-04a5-472c-98be-d68da4a10730.png)
![image](https://user-images.githubusercontent.com/90480884/140435992-3fff522f-da50-443f-9f88-5ddb70ef80b5.png)
![image](https://user-images.githubusercontent.com/90480884/140436020-d48337c0-cc18-4857-9b7a-24830ff2868c.png)
![image](https://user-images.githubusercontent.com/90480884/140436038-7260f2b9-9047-4432-9173-2ac9bde4b5d0.png)
![image](https://user-images.githubusercontent.com/90480884/140436054-d9f75d0c-e012-4ca5-846f-e711e5cb0dfd.png)
![image](https://user-images.githubusercontent.com/90480884/140436209-bdb17493-7585-43d8-aab0-6b3e26e77a9d.png)
-Looks to be a different size due to size of prntScrn
- All are same size as to maintain constant size on Mac's component

2021-11-05 02:15 UTC, Hunterjdf commented
Changed the if-else monstrosity into a much nicer switch statement.

2021-11-05 02:17 UTC, ralph-dev requested changes

2021-11-05 02:17 UTC, ralph-dev commented on src/Containers/LimitedTimeBanner/LimitedTimeBanner.tsx
> +const alterTime = (value:number)  => {
JSDOC

2021-11-05 02:17 UTC, ralph-dev commented on src/Containers/LimitedTimeBanner/LimitedTimeBanner.tsx
> +        case (value >= 168 && value < 8736):
You should use const for these magic numbers to give them meaning

2021-11-05 13:33 UTC, ralph-dev requested changes

2021-11-05 13:33 UTC, ralph-dev commented on src/Containers/LimitedTimeBanner/LimitedTimeBanner.stories.tsx
> +
Remove extra line

2021-11-05 13:33 UTC, ralph-dev commented on src/Containers/LimitedTimeBanner/LimitedTimeBanner.tsx
> +const hoursInDay = 24;
Constanta should be all caps

2021-11-05 13:33 UTC, ralph-dev commented on src/Containers/LimitedTimeBanner/LimitedTimeBanner.tsx
> +const hoursInDay = 24;
HOURS_IN_DAY

2021-11-05 17:22 UTC, Hunterjdf commented
![image](https://user-images.githubusercontent.com/90480884/140551782-c73f93e0-db5e-4636-a1dc-8dd97f931990.png)
![image](https://user-images.githubusercontent.com/90480884/140551813-0f580249-3635-4132-aca0-213db7207ffd.png)
![image](https://user-images.githubusercontent.com/90480884/140551839-89a47204-a936-4384-addd-4f8d61642836.png)
![image](https://user-images.githubusercontent.com/90480884/140551894-c4bb4c58-092d-49e3-8514-2df885e94f03.png)
![image](https://user-images.githubusercontent.com/90480884/140552034-68cb1196-5904-4ace-b909-4cd512d7b50a.png)
- switched out the main function with moment.duration(value,'minutes').humanize();
- Now it works of a base of  minutes with 120 as default 
- Slightly different wording but it works 
- Other code to catch 0 or less or over a year (min + max)
- comments for Props and function added, based of of other components (those with comments)

2021-11-05 17:42 UTC, ralph-dev approved these changes
Lgtm but fix comments and have team review once

2021-11-05 17:42 UTC, ralph-dev commented on src/Containers/LimitedTimeBanner/LimitedTimeBanner.tsx
> +console.log(moment.now());
Remove log. Use LogPoints by Visual Studio Code

2021-11-06 21:10 UTC, Hunterjdf commented
Log Turned out to be unnecessary. 
Comments style based on Analytics.tsx

2021-11-07 13:19 UTC, ralph-dev approved these changes
Lgtm

2021-11-07 13:19 UTC, ralph-dev commented on src/Containers/LimitedTimeBanner/LimitedTimeBanner.tsx
> +moment.now();
What's this?

2021-11-07 13:19 UTC, ralph-dev commented on src/Containers/LimitedTimeBanner/LimitedTimeBanner.tsx
> +    }
Or don't show banner :)

2021-11-07 19:31 UTC, Hunterjdf commented
Sir I was having a problem with merging my branch back into cheapreats:master. The changes I a making conflict with what has already been committed last week during the meeting. The "resolve conflicts" button appears unviable do to complexity. The other option is a manual merge however I am less than confident in that procedure as I am not sure where in github I can resolve these conflicts.

2021-11-07 19:33 UTC, ralph-dev commented
> Sir I was having a problem with merging my branch back into cheapreats:master. The changes I a making conflict with what has already been committed last week during the meeting. The "resolve conflicts" button appears unviable do to complexity. The other option is a manual merge however I am less than confident in that procedure as I am not sure where in github I can resolve these conflicts. 

Branch off master latest, and copy paste the files into the new branch don't fix the conflicts just start again.

2022-01-21 00:00 UTC, closed without merging