Cem 2595 info header
cheapreats/react-ui-library pull request #399
Opened 2021-11-11 05:45 UTC by Hunterjdf

Simple component, Let me know if there is are issues with how it is constructed.

2021-11-11 06:45 UTC, ralph-dev requested changes
Where is picture in PR

2021-11-11 06:45 UTC, ralph-dev commented on src/Containers/InfoHeader/InfoHeader.tsx
> +</InfoHeaderStyle>
Fix indentation

2021-11-11 06:45 UTC, ralph-dev commented on src/Containers/InfoHeader/InfoHeader.tsx
> +    <InfoHeaderStyle>
Spread props

2021-11-11 17:07 UTC, Hunterjdf commented
![image](https://user-images.githubusercontent.com/90480884/141339303-7f5021b3-77c5-42e6-b0f3-4fb197bc2593.png)
Component Image

2021-11-12 23:59 UTC, Hunterjdf commented
![image](https://user-images.githubusercontent.com/90480884/141596824-30605cf9-f83e-488a-b9ba-ccad4d315af0.png)

2021-11-13 00:00 UTC, Hunterjdf commented
Zoomed in view. 
- Updated with spread header props

2021-11-13 15:39 UTC, ralph-dev requested changes
Waiting for in meeting changes

2021-11-13 15:39 UTC, ralph-dev commented on src/Containers/InfoHeader/InfoHeader.tsx
> +const InfoHeaderStyle = styled(Heading)`
It's not a Style, it's a text

2021-11-14 01:07 UTC, Hunterjdf commented
Sorry sir, in regards to in meeting changes are you referencing the changes we made during the meeting or are referencing something else ? 
I think I may have missed something that you said, while focusing on the header props.  
Aside from the fixed comment, what was it that I didn't get?

2021-11-15 12:48 UTC, ralph-dev approved these changes
Lgtm

2021-11-19 02:08 UTC, merged