GR-CRM - CEM-2585 - Tree Accordion
cheapreats/react-ui-library pull request #409
Opened 2021-11-17 09:19 UTC by Madmanmayson

Finished Tree Accordion with SVG drawing animations on collapsing and expanding. Instead of chaining a bunch of smaller SVG paths to connect them together, I went for a more simplified approach of stacking the paths on top of each other and using different animation times to achieve a similar drawing effect. I also added an optional counter next to the arrow showing how many child components are in the accordion. In the storybook example its also given a width of 15% screen width to help showcase the arrow being at the right hand side of the component better.

Component Design:
![image](https://user-images.githubusercontent.com/11225158/142171686-60061e5b-7e53-47af-a20e-b278d1444f0b.png)

Collapsing and expanding transition in action:
https://user-images.githubusercontent.com/11225158/142171300-889b5f4a-29db-4d7a-a462-90a7eba71fc0.mp4
(Sorry about the watermark, quickest screen recording software I could find)

2021-11-17 14:09 UTC, ralph-dev requested changes
Looks great! Small fixes needed

2021-11-17 14:09 UTC, ralph-dev commented on src/Containers/TreeAccordion/TreeAccordion.stories.tsx
> +export const Basic: Story<ITreeAccordionProps> = (args) => (
And a story with no children

2021-11-17 14:09 UTC, ralph-dev commented on src/Containers/TreeAccordion/TreeAccordion.tsx
> +        totalChildrenHeight = childHeights.reduce((a, b) => a + b, 0);
What is a b, use clearer variable names

2021-11-17 14:09 UTC, ralph-dev commented on src/Containers/TreeAccordion/TreeAccordion.tsx
> +                    return( <Path d={SVGPath} pathLength={1} isExpanded={isExpanded} animationTime={animationTimePerChild * (index + ANIMATION_INDEX_SHIFT)}/>);
{...pathProps}

2021-11-17 18:57 UTC, Madmanmayson commented
Most of those small issues should be fixed now, had to rework some more logic that came up when testing the new stories (wasn't handling margins for height calculations and errored out when children were undefined) but those issues should be resolved now.

2021-11-23 02:44 UTC, ralph-dev commented on src/Containers/TreeAccordion/TreeAccordion.tsx
> +    stroke: black;
Bump

2021-11-23 02:45 UTC, ralph-dev commented on src/Containers/TreeAccordion/TreeAccordion.tsx
> +    stroke: black;
I meant like also expose, Color of Path, and use that from Props since that will be a common thing to override here

2021-11-23 02:45 UTC, ralph-dev approved these changes
Lgtm, just need to make color of path changing more flexible

2021-11-23 19:55 UTC, Madmanmayson commented on src/Containers/TreeAccordion/TreeAccordion.tsx
> +    stroke: black;
Oh whoops sorry about that, should be fixed now.

2021-11-25 19:54 UTC, merged