Initial Commit CEM2594
cheapreats/react-ui-library pull request #411
Opened 2021-11-18 17:57 UTC by mfnisbetLU

Initial Commit for CEM2594 Reach Indicator. To do: change colors to theme colors in progressbar, render progressbar and engagement box depending on if props have values (combine reach and engagement progress bars, and render the box depending on if post engagements and or people reached have values). Demo video below: 

https://user-images.githubusercontent.com/91333450/142470463-eb33740a-e3e8-4f37-829d-40851db89640.mp4

2021-11-18 19:40 UTC, ralph-dev reviewed
It's coming together!

2021-11-18 19:40 UTC, ralph-dev commented on src/Containers/ReachIndicator/ReachIndicator.tsx
> +    engageNum: number,
Don't forget documentation I want to understand how these props are being used

2021-11-18 19:40 UTC, ralph-dev commented on src/Containers/ReachIndicator/ReachIndicator.tsx
> +        <EngagementBox {...props}>
Remember you should have one engagement box and have two instances of the component next to each other

2021-11-20 17:01 UTC, ralph-dev requested changes
Waiting for in meeting changes

2021-11-21 04:53 UTC, mfnisbetLU commented
Sorry, I had the changes done this morning, but I wanted to make sure everything was right. I remember you asking for the display on a small mobile device, so attached is that, and a case for a very long indicator name.
![Reach indicator small mobile](https://user-images.githubusercontent.com/91333450/142750056-480971e6-f610-488f-a461-2040a9cb8b2b.PNG)
![Reach indicator verbose](https://user-images.githubusercontent.com/91333450/142750058-b298f366-dd94-44e4-8d34-4ff616b8876a.PNG)

2021-11-22 15:04 UTC, ralph-dev commented on src/Containers/ReachIndicator/ReachIndicator.tsx
> +    indicatorName: string, // Reach indicator display name (people reached/post engagements)
Format this correct 

/* reach */
indictora

2021-11-22 15:05 UTC, ralph-dev commented on src/Containers/ReachIndicator/ReachIndicator.tsx
> +            </>
remove this empty one, you don't need it anymore

2021-11-22 15:05 UTC, ralph-dev approved these changes
LGTM, please fix small changes first

2021-11-22 17:59 UTC, merged