Cem 2595 info header try3
cheapreats/react-ui-library pull request #418
Opened 2021-11-21 00:34 UTC by Hunterjdf

Basic:
![image](https://user-images.githubusercontent.com/90480884/142744806-08b83546-9725-49f1-9faf-788087286074.png)
Long:
![image](https://user-images.githubusercontent.com/90480884/142744846-3dd5f4bd-6c88-4743-a8ed-f34f27faaee5.png)
Nothing: 
![image](https://user-images.githubusercontent.com/90480884/142744867-c77c8524-d9d9-43bf-ba35-237ffc34f13b.png)
- Could add functionally (I believe you told me not to during the meeting)  if requested - otherwise will start next component.

2021-11-21 12:53 UTC, ralph-dev approved these changes
Lgtm , let's start the next component

2021-11-21 12:54 UTC, ralph-dev commented
It would be great to add the onMouseEnter / Leave storybook actions here so you have events to hook onto.

https://upmostly.com/tutorials/react-onhover-event-handling-with-examples

2021-11-21 23:51 UTC, Hunterjdf commented
onMouseEnter / Leave as specified by the provided documentation. 
![image](https://user-images.githubusercontent.com/90480884/142783850-8a8cf015-4d4d-4814-b632-d3c34fbb9a2c.png)
Now the icon does not exist unless you mouse over it. 
That's just an example to demonstrate the onMouseEnter.
If you wanted it implemented in a different way, let me know.

2021-11-22 01:48 UTC, ralph-dev commented
I was more talking about, OnMouseEnter, show a tooltip on the info icon :). But just emit the event don't actually show a tooltip 😅.

Interesting UX 😅 you made here 🤣

2021-11-22 06:23 UTC, Hunterjdf commented
![image](https://user-images.githubusercontent.com/90480884/142810433-7875fcd4-d766-4237-b78e-72b1f6ddf5db.png)
![image](https://user-images.githubusercontent.com/90480884/142810515-932d0741-b839-4b93-9e2d-a73eec4c6509.png)

2021-11-22 06:32 UTC, Hunterjdf commented
Yea that's a bit of an odd way to do it now that I look at it. 
This should be closer to what you had in mind. 
- I am doing the duo component with Russel, and so I was  more focused on trying to help him on his draggable list attempt.

2021-11-22 15:03 UTC, ralph-dev commented on src/Containers/InfoHeader/InfoHeader.tsx
> +        </ToolTipText>
This Tooltip should be defined by the Storyfile. You can have a default tooltip but let the person using this component pass in their own tooltip / text explanations component.

Not everything will have the same explanation

2021-11-22 15:04 UTC, ralph-dev reviewed
Almost there!

2021-11-22 19:21 UTC, Hunterjdf commented
Default: 
![image](https://user-images.githubusercontent.com/90480884/142922244-ea054aff-a2db-4724-8527-d62841a2a654.png)
With args: 
![image](https://user-images.githubusercontent.com/90480884/142922168-3b679c3c-063a-4b49-b466-6edd9240ea1c.png)

2021-11-25 03:43 UTC, Hunterjdf commented
Hello sir, I just wanted to check in and make sure that what I have is good to publish- I finished it a few days ago to work on this weeks component and was just waiting for you to confirm the last commit. 
I would like to commit it as it had been finished for 2 days now and I don't want the hassle of trying to un-merge and re-merge again so I wont commit unless you confirm that there will be no more changes.

2021-11-25 04:18 UTC, ralph-dev requested changes
You aren't emitting the event correctly. Let's discuss in the meeting.

2021-11-26 22:32 UTC, Hunterjdf commented
![image](https://user-images.githubusercontent.com/90480884/143659093-3562842e-46a2-4011-bc5e-94265680e94b.png)
- Actions example

2021-11-26 23:01 UTC, ralph-dev approved these changes
LGTM

2021-11-27 02:56 UTC, merged