CEM-2611 ThemeSwitch
cheapreats/react-ui-library pull request #441
Opened 2022-01-23 01:39 UTC by Zhuk314

# Don't Forget to:
- Follow Naming Conventions (School if applicable or your name - CEM-TICKET_NUMBER - Short Title) (Ex: Ralph - CEM1234 - Button Component)
- [Mark Ralph as a Reviewer for this PR](https://wolfbeacon.atlassian.net/wiki/spaces/CW/pages/1641873414/3.+Wrapping+Up+Your+Ticket)
- Attach a Picture or a GIF to your PR for visualization / UI/UX Test.

# Got a Review?
Make sure to ask for a re-review after resolving the comments, by clicking the refresh icon!

2022-01-23 12:54 UTC, ralph-dev requested changes
You'll want to transition the Colors that are changing so it doesn't pop the color difference. Ex your going from white to black instead of doing it instantly, do it with a color transition

2022-01-25 05:02 UTC, ralph-dev requested changes
Typings need to be stricter, Gif needed for PR

2022-01-25 05:02 UTC, ralph-dev commented on src/Inputs/ThemeSwitch/ThemeSwitch.tsx
> +    movingDivColor: string;
Try to use a more specific type 
"Cow" would not be correct here

2022-01-29 20:19 UTC, Zhuk314 commented
![Animation](https://user-images.githubusercontent.com/78105676/151676295-932eaaf4-2445-45f2-b65f-e1e4a69c4849.gif)

2022-01-30 13:58 UTC, ralph-dev commented
@Zhuk314 can you provide another story with unequal text length
Ex:

Light,  super super dark, the darkest dark dark you've ever seen

Just as a test for the component :)

2022-01-31 07:54 UTC, Zhuk314 commented
![Animation_ThemeSwitchUnequalText](https://user-images.githubusercontent.com/78105676/151757074-6682e784-dd17-4969-87e1-107036814ef7.gif)

Animation with Unequal Text.

2022-01-31 12:45 UTC, ralph-dev approved these changes
LGTM

2022-01-31 17:55 UTC, merged